services:

  nginx:
    ports:
      - "${PORT_NGINX:-8000}:80"

  client:
    command: sh -lc "npm install && npm run dev -- --hostname 0.0.0.0 --port 3000"

  admin:
    command: sh -lc "npm install && npm run dev -- --host 0.0.0.0 --port 3000"

  web_mobile:
    command: sh -lc "npm install && npx expo start --web --host 0.0.0.0 --port 19006"
